[package]
name = "sexy-soc"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"
ctrlc = "3.4.5"
hex = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha3 = "0.10.8"
tokio = "1.42.0"


[dependencies.pnet]
version = "0.35.0"
