[package]
name = "sexy-soc"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha3 = "0.10.8"


[dependencies.pnet]
version = "0.35.0"
